name: Docker Android Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ docker-build ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Android APK with Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          cimg/android:2024.01.1 \
          bash -c "
            # Setup environment
            export ANDROID_HOME=/home/circleci/android-sdk
            export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools
            
            # Accept licenses
            yes | \$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
            
            # Install required components
            \$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager 'platforms;android-33' 'build-tools;33.0.2'
            
            # Make gradlew executable
            chmod +x ./gradlew
            
            # Build the APK
            ./gradlew assembleDebug --no-daemon --stacktrace
          "
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-android-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30